# Setup
title:        Karthikeyan v Page
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name: karthikeyan veera
  url: http://linkedin.com/in/kvvchetty 
  email: kvvchety@outlook.com
  github: kvvchetty
  twitter: kvvchetty

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown