# Setup
title:        SelFile
tagline:      Programmer  GitHub Pages
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Karthikeyan veera
  url:        http://github.com/kvvchetty 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown